import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../services/api';
import { useApp } from '../contexts/AppContext';

const RequestVideo = () => {
  const [formData, setFormData] = useState({
    topic: '',
    duration: 300,
    style: 'educational',
    language: 'en'
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();
  const { dispatch } = useApp();

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    
    try {
      const response = await api.post('/content/request', formData);
      // Update context with new request
      dispatch({
        type: 'ADD_VIDEO_REQUEST',
        payload: response.data.data
      });
      
      alert('Your video request has been submitted! It will be generated by our AI.');
      navigate('/dashboard');
    } catch (error) {
      console.error('Error submitting video request:', error);
      setError(error.response?.data?.error || 'Failed to submit video request');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="main-container">
      <div className="request-video-container">
        <h2 className="section-title">Create AI Video</h2>
        {error && <div className="error-message">{error}</div>}
        <form onSubmit={handleSubmit} className="request-form">
          <div className="form-group">
            <label htmlFor="topic">Topic</label>
            <input
              type="text"
              id="topic"
              name="topic"
              value={formData.topic}
              onChange={handleChange}
              placeholder="Enter the topic for your AI video..."
              required
              disabled={loading}
            />
          </div>
          
          <div className="form-group">
            <label htmlFor="duration">Duration (seconds)</label>
            <input
              type="range"
              id="duration"
              name="duration"
              min="10"
              max="3600"
              value={formData.duration}
              onChange={handleChange}
              disabled={loading}
            />
            <span>{formData.duration} seconds</span>
          </div>
          
          <div className="form-group">
            <label htmlFor="style">Style</label>
            <select
              id="style"
              name="style"
              value={formData.style}
              onChange={handleChange}
              disabled={loading}
            >
              <option value="educational">Educational</option>
              <option value="entertainment">Entertainment</option>
              <option value="documentary">Documentary</option>
              <option value="tutorial">Tutorial</option>
              <option value="explainer">Explainer</option>
            </select>
          </div>
          
          <div className="form-group">
            <label htmlFor="language">Language</label>
            <select
              id="language"
              name="language"
              value={formData.language}
              onChange={handleChange}
              disabled={loading}
            >
              <option value="en">English</option>
              <option value="es">Spanish</option>
              <option value="fr">French</option>
              <option value="de">German</option>
              <option value="ja">Japanese</option>
              <option value="zh">Chinese</option>
              <option value="hi">Hindi</option>
              <option value="ar">Arabic</option>
            </select>
          </div>
          
          <button type="submit" className="cta-button primary" disabled={loading}>
            {loading ? (
              <>
                <i className="fas fa-spinner fa-spin"></i> Generating...
              </>
            ) : (
              <>
                <i className="fas fa-magic"></i> Generate Video
              </>
            )}
          </button>
        </form>
      </div>
    </div>
  );
};

export default RequestVideo;
